### ISSUE TITLE
Single variant single trait runs fail to generate QQplot

### ISSUE THREAD

**Issue by roskamsh** [TARGENE/TargeneCore.jl#199]
Upon running the targene-pipeline (v0.11.0) using a single variant and single trait, the final step GenerateOutputs() fails. Upon further inspection, this only occurs when the number of non-NA P-values per-estimator is 1. This would occur when you are running TarGene with only a single variant and single trait (currently experiencing this when reproducing FTO variant on BMI results on the AoU cohort).

Suggested changes:
- Make QQplot generation optional when only a single p-value (per-estimator) is present.
- Update targene-pipeline to make this output QQplot.png optional.

**Comment by olivierlabayle** [comment]
What is the reason behind the NA in this case?
